package com.skych.fullsystem.dao;

import com.skych.fullsystem.model.AccountRoleRel;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountRoleRelDao {
    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("accountId") Integer accountId, @Param("roleId") Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int insert(AccountRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    List<AccountRoleRel> selectAll();
}