package com.skych.fullsystem.dao;

import com.skych.fullsystem.model.Right;
import java.util.List;

public interface RightDao {
    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int insert(Right record);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    Right selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    List<Right> selectAll();

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int updateByPrimaryKey(Right record);
}