package com.skych.fullsystem.dao;

import com.skych.fullsystem.model.RoleRightRel;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleRightRelDao {
    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleId") Integer roleId, @Param("rightId") Integer rightId);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int insert(RoleRightRel record);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    List<RoleRightRel> selectAll();
}