package com.skych.fullsystem.dao;

import com.skych.fullsystem.model.Role;
import java.util.List;

public interface RoleDao {
    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
    
     * @mbg.generated
     */
    int updateByPrimaryKey(Role record);
}